title = "Alhambra Luckenwalde"
tag_line = "Musik- und Kulturförderverein e.V."

[social.instagram]
title = "Instagram"
url = "https://www.instagram.com/alhambra_luckenwalde"

[social.facebook]
title = "Facebook"
url = "https://www.facebook.com/musikundkultur"

[[events]]
date = "28. Oktober"
title = "Halloween-Party" 

[[events]]
date = "4. November"
title = "Geschlossene Gesellschaft" 

[[events]]
date = "18. November"
title = "Kneipenquiz" 

[[events]]
date = "2. Dezember"
title = "Vorverkaufsparty Weihnachtskonzert" 

[[events]]
date = "9. Dezember"
title = "Lesung" 

[[events]]
date = "25. Dezember"
title = "Weihnachtskonzert" 
