---
name: release
on:
  workflow_dispatch:
    inputs:
      force-deploy:
        required: true
        type: boolean
        description: Deploy app even if no release was created.
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - name: Run release-please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          bump-minor-pre-major: true
          package-name: wohnzimmer
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

  deploy:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event.inputs.force-deploy == 'true' }}
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy
